version: '3.1'

services:

  display:
    restart: always
    hostname: display
    container_name: display
    image: bskjon/display:latest
    network_mode: "host"
    environment:
      METER_PLATFORM: TIBBER
      METER_PLATFORM_TOKEN: <token>
    volumes:
      - ./data/zookeeper:/var/lib/zookeeper/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

