package no.iktdev.display.model

enum class Views {
    GRAPH_ELECTRICITY_PRICE,
    GRAPH_ELECTRICITY_CONSUMPTION,
    ELECTRICITY_PRICE,
    ELECTRICITY_PRICE_LEVEL,
    ELECTRICITY_PRICE_MIN,
    ELECTRICITY_PRICE_MAX,
    ELECTRICITY_PRICE_AVG,
    ELECTRICITY_METER_INITIAL,

    WEATHER,
    CLIMATE,
    TEMPERATURE,
    PRECIPITATION,
    CARBON_DIOXIDE,
    HUMIDITY,
    WIND

}